import headphone from './headphone.png'

const categories = [
  { name: "Electronics", image: headphone },
  { name: "Fashion", image: headphone },
  { name: "Shoes", image: headphone },
  { name: "Furniture", image: headphone },
  { name: "Beauty", image: headphone },
  { name: "Books", image: headphone },
  { name: "Sports", image: headphone },
  { name: "Toys", image: headphone },
];

const products = [
  {
    _id: "1",
    name: "Wireless Headphones",
    discount: 20,
    price: 2999,
    image: headphone,
  },
  {
    _id: "2",
    name: "Smart Watch",
    discount: 15,
    price: 4999,
    image: headphone,
  },
  {
    _id: "3",
    name: "Running Shoes",
    discount: 30,
    price: 2499,
    image: headphone,
  },
  {
    _id: "4",
    name: "Bluetooth Speaker",
    discount: 10,
    price: 1999,
    image: headphone,
  },
  {
    _id: "5",
    name: "Laptop Backpack",
    discount: 25,
    price: 1499,
    image: headphone,
  },
  {
    _id: "6",
    name: "Gaming Mouse",
    discount: 18,
    price: 999,
    image: headphone,
  },
  {
    _id: "7",
    name: "Cotton T-Shirt",
    discount: 40,
    price: 699,
    image: headphone,
  },
  {
    _id: "8",
    name: "Sunglasses",
    discount: 12,
    price: 899,
    image: headphone,
  },
];


const carts = [
  {
    image: headphone,
    name: "Wireless Mouse",
    price: 25.99,
    qty: 2,
  },
  {
    image: headphone,
    name: "Mechanical Keyboard",
    price: 79.99,
    qty: 1,
  },
  {
    image: headphone,
    name: "USB-C Hub",
    price: 39.5,
    qty: 3,
  },
  {
    image: headphone,
    name: "27-inch Monitor",
    price: 249.99,
    qty: 1,
  },
  {
    image: headphone,
    name: "Laptop Stand",
    price: 34.99,
    qty: 2,
  },
];


const addresses = [
  {
    name: "John Doe",
    phoneNumber: "9876543210",
    street: "123 Maple Street",
    city: "New York",
    state: "New York",
    postalCode: "10001",
    landmark: "Near Central Park",
    addressType: "Home",
    isDefault: true,
  },
  {
    name: "Emma Wilson",
    phoneNumber: "9123456789",
    street: "45 Oak Avenue",
    city: "Los Angeles",
    state: "California",
    postalCode: "90012",
    landmark: "Opposite City Library",
    addressType: "Work",
    isDefault: false,
  },
  {
    name: "Michael Brown",
    phoneNumber: "9988776655",
    street: "78 Pine Road",
    city: "Chicago",
    state: "Illinois",
    postalCode: "60601",
    landmark: "Next to Green Mall",
    addressType: "Home",
    isDefault: false,
  },
  {
    name: "Sophia Davis",
    phoneNumber: "9012345678",
    street: "210 River View",
    city: "Houston",
    state: "Texas",
    postalCode: "77002",
    landmark: "Near City Hospital",
    addressType: "Office",
    isDefault: false,
  },
  {
    name: "Liam Johnson",
    phoneNumber: "9765432109",
    street: "15 Sunset Boulevard",
    city: "Phoenix",
    state: "Arizona",
    postalCode: "85001",
    landmark: "Behind Metro Station",
    addressType: "Other",
    isDefault: false,
  }
];


const productTable = [
  {
    id: 1,
    image: headphone,
    name: "Wireless Mouse",
    category: "Electronics",
    price: 799,
    stock: 45,
    status: "Active",
  },
  {
    id: 2,
    image: headphone,
    name: "Gaming Keyboard",
    category: "Electronics",
    price: 2499,
    stock: 18,
    status: "Active",
  },
  {
    id: 3,
    image: headphone,
    name: "Running Shoes",
    category: "Footwear",
    price: 3499,
    stock: 12,
    status: "Active",
  },
  {
    id: 4,
    image: headphone,
    name: "Cotton T-Shirt",
    category: "Clothing",
    price: 599,
    stock: 80,
    status: "Active",
  },
  {
    id: 5,
    image: headphone,
    name: "Bluetooth Speaker",
    category: "Electronics",
    price: 1899,
    stock: 0,
    status: "InActive",
  },
  {
    id: 6,
    image: headphone,
    name: "Coffee Mug",
    category: "Home & Kitchen",
    price: 299,
    stock: 120,
    status: "Active",
  },
  {
    id: 7,
    image: headphone,
    name: "Office Chair",
    category: "Furniture",
    price: 6999,
    stock: 7,
    status: "Active",
  },
  {
    id: 8,
    image: headphone,
    name: "Smart Watch",
    category: "Wearables",
    price: 8999,
    stock: 23,
    status: "Active",
  },
  {
    id: 9,
    image: headphone,
    name: "Backpack",
    category: "Accessories",
    price: 1499,
    stock: 35,
    status: "Active",
  },
  {
    id: 10,
    image: headphone,
    name: "Water Bottle",
    category: "Sports",
    price: 499,
    stock: 0,
    status: "InActive",
  },
];


const categoryTable = [
  {
    id: 1,
    image: headphone,
    name: "Electronics",
    slug: "electronics",
    description: "Latest gadgets, devices, and electronic accessories.",
    status: "active",
  },
  {
    id: 2,
    image: headphone,
    name: "Fashion",
    slug: "fashion",
    description: "Trendy clothing, footwear, and fashion accessories.",
    status: "active",
  },
  {
    id: 3,
    image: headphone,
    name: "Home & Kitchen",
    slug: "home-kitchen",
    description: "Furniture, kitchen essentials, and home decor items.",
    status: "active",
  },
  {
    id: 4,
    image: headphone,
    name: "Beauty & Personal Care",
    slug: "beauty-personal-care",
    description: "Skincare, makeup, grooming, and wellness products.",
    status: "inActive",
  },
  {
    id: 5,
    image: headphone,
    name: "Sports & Fitness",
    slug: "sports-fitness",
    description: "Equipment, apparel, and accessories for sports and fitness.",
    status: "active",
  },
  {
    id: 6,
    image: headphone,
    name: "Books",
    slug: "books",
    description: "Fiction, non-fiction, educational, and children's books.",
    status: "active",
  },
  {
    id: 7,
    image: headphone,
    name: "Toys & Games",
    slug: "toys-games",
    description: "Fun toys, puzzles, and games for all age groups.",
    status: "inActive",
  },
  {
    id: 8,
    image: headphone,
    name: "Automotive",
    slug: "automotive",
    description: "Car accessories, tools, and vehicle maintenance products.",
    status: "active",
  },
  {
    id: 9,
    image: headphone,
    name: "Groceries",
    slug: "groceries",
    description: "Daily essentials, packaged foods, and beverages.",
    status: "active",
  },
  {
    id: 10,
    image: headphone,
    name: "Pet Supplies",
    slug: "pet-supplies",
    description: "Food, toys, grooming, and accessories for pets.",
    status: "inActive",
  },
];


const subCategoryTable = [
  {
    id: 1,
    name: "Smartphones",
    slug: "smartphones",
    category: "Electronics",
    status: "active",
  },
  {
    id: 2,
    name: "Laptops",
    slug: "laptops",
    category: "Electronics",
    status: "active",
  },
  {
    id: 3,
    name: "Men's Clothing",
    slug: "mens-clothing",
    category: "Fashion",
    status: "active",
  },
  {
    id: 4,
    name: "Women's Clothing",
    slug: "womens-clothing",
    category: "Fashion",
    status: "active",
  },
  {
    id: 5,
    name: "Cookware",
    slug: "cookware",
    category: "Home & Kitchen",
    status: "active",
  },
  {
    id: 6,
    name: "Furniture",
    slug: "furniture",
    category: "Home & Kitchen",
    status: "inActive",
  },
  {
    id: 7,
    name: "Skincare",
    slug: "skincare",
    category: "Beauty & Personal Care",
    status: "active",
  },
  {
    id: 8,
    name: "Makeup",
    slug: "makeup",
    category: "Beauty & Personal Care",
    status: "active",
  },
  {
    id: 9,
    name: "Gym Equipment",
    slug: "gym-equipment",
    category: "Sports & Fitness",
    status: "active",
  },
  {
    id: 10,
    name: "Outdoor Sports",
    slug: "outdoor-sports",
    category: "Sports & Fitness",
    status: "inActive",
  },
  {
    id: 11,
    name: "Fiction",
    slug: "fiction",
    category: "Books",
    status: "active",
  },
  {
    id: 12,
    name: "Educational Books",
    slug: "educational-books",
    category: "Books",
    status: "active",
  },
  {
    id: 13,
    name: "Board Games",
    slug: "board-games",
    category: "Toys & Games",
    status: "active",
  },
  {
    id: 14,
    name: "Action Figures",
    slug: "action-figures",
    category: "Toys & Games",
    status: "inActive",
  },
  {
    id: 15,
    name: "Car Accessories",
    slug: "car-accessories",
    category: "Automotive",
    status: "active",
  },
  {
    id: 16,
    name: "Motorbike Accessories",
    slug: "motorbike-accessories",
    category: "Automotive",
    status: "active",
  },
  {
    id: 17,
    name: "Snacks",
    slug: "snacks",
    category: "Groceries",
    status: "active",
  },
  {
    id: 18,
    name: "Beverages",
    slug: "beverages",
    category: "Groceries",
    status: "active",
  },
  {
    id: 19,
    name: "Dog Supplies",
    slug: "dog-supplies",
    category: "Pet Supplies",
    status: "active",
  },
  {
    id: 20,
    name: "Cat Supplies",
    slug: "cat-supplies",
    category: "Pet Supplies",
    status: "inActive",
  },
];

export { categories, products, carts, addresses, productTable, categoryTable, subCategoryTable };